# name of the executable and header file
NAME = brazilnuts

# change this to 1 or 0 depending if you want a pretty plot,
# not sure what you want otherwise
DOPLOT = 1
FPS    = 1
POINTS = 0
OPENMP = 0

# standard compile options for the c++ executable
ENTBODY  := ${ENTBODY}
FULLPATH := `pwd`/$(NAME)

include ${ENTBODY}/examples/common.mk
