#define CONST_PBC               {1,0}
#define CONST_PARTICLECOUNT     512*32
#define CONST_KICKFORCE         5.0

#define INIT_RAYLEIGHTAYLOR_FRACTION 0.3
#define FUNCTION_INIT           INIT_RAYLEIGHTAYLOR

#define CONST_CUTOFF_FACTOR     1.0 
#define FORCE_MORSE_EPSILON     2530.0
#define FORCE_MORSE_ALPHA       0.10
#define FUNCTION_FORCE_PAIR     FORCE_MORSE_2POP

#define FORCE_DAMPING_COEFF     0.4
#define FORCE_DAMPING_SPEED     0.0
#define FORCE_GRAVITY_G         0.2
#define FUNCTION_FORCE_GLOBAL   {FORCE_DAMPING FORCE_GRAVITY FORCE_KICK FORCE_THERMAL}
