#define CONST_PBC               {1,1}
#define CONST_PARTICLECOUNT     512*18
#define CONST_KICK_FORCE        0.1f
#define CONST_FRAME_SKIP        1
#define CONST_COLOR_FACTOR      90.0f

#define INIT_RANDOM_FRACTION    0.97 
#define FUNCTION_INIT           INIT_RANDOM

#define FORCE_HERTZ_EPSILON     180.0f
#define FUNCTION_FORCE_PAIR     FORCE_HERTZ

#define FORCE_DAMPING_COEFF     0.3f
#define FORCE_DAMPING_SPEED     0.0f
#define FORCE_KICK_CONST        26.0f
#define FUNCTION_FORCE_GLOBAL   {FORCE_DAMPING FORCE_KICK}

