#define PBC                     {1,1}
#define PARTICLECOUNT           512*16

#define FUNCTION_INIT           INIT_RANDOM

#define FORCE_HERTZ_EPSILON     150.0
#define FUNCTION_FORCE_PAIR     FORCE_HERTZ

#define FORCE_DAMPING_COEFF     1.0
#define FUNCTION_FORCE_GLOBAL   {FORCE_DAMPING FORCE_KICK}

